version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.06
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            docker build . -t bog13/lettings
            docker save -o lettings.tar bog13/lettings
  test:
    docker:
      - image: cimg/python:3.11.12
    steps:
      - checkout
      - run: 
          name: Test the app
          command: |
            pip install -r requirements.txt
            pytest
  deploy:
    docker:
      - image: cimg/base:2022.06 
    steps:
      - checkout
      - run:
          name: Deploy to AWS
          command: echo "=> Deploy"

workflows:
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test

