version: 2.1

jobs:
  build:
    docker:
      - image: debian
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: |
            apt install docker.io
            systemctl start docker
            docker build . -t bog13/lettings
  test:
    docker:
      - image: alpine:3.15
    steps:
      - checkout
      - run: 
          name: Test the app
          command: echo "=> Test"
  deploy:
    docker:
      - image: alpine:3.15
    steps:
      - checkout
      - run:
          name: Deploy to AWS
          command: echo "=> Deploy"

workflows:
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test

