version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: 
          name: Test the app
          command: |
            pip install -r requirements.txt
            pytest
  build:
    docker:
      - image: cimg/base:2022.06
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            docker build . -t bog13/lettings:$CIRCLE_SHA1
            echo -n "$DOCKER_HUB_PASSWORD" | docker login --username $DOCKER_HUB_USER --password-stdin
            docker push bog13/lettings:$CIRCLE_SHA1
  deploy:
    docker:
      - image: cimg/base:2022.06
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy to AWS 
          command: |
            sudo apt install -y sshpass
            sshpass -p $WEB_PASSWORD ssh $WEB_USER@$WEB_SERVER bash deploy.sh

workflows:
  test_and_build_deploy:
    jobs:
      - test
      - build:
          requires:
          - test
      - deploy:
          requires:
            - build

