version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: 
          name: Test the app
          command: |
            pip install -r requirements.txt
            pytest
  build:
    docker:
      - image: cimg/base:2022.06
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            docker build . -t bog13/lettings:$CIRCLE_SHA1
            sudo apt update
            sudo apt install -y pass
            mkdir -p $HOME/.docker
            echo "{\"credsStore\": \"pass\"}" > $HOME/.docker/config.json
            ssh -o StrictHostKeyChecking=accept-new $WEB_USER@$WEB_SERVER cat secret.txt | docker login -u bog13 --password-stdin
            docker push bog13/lettings:$CIRCLE_SHA1
            docker logout
  deploy:
    docker:
      - image: cimg/base:2022.06
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy to AWS 
          command: |
            ssh -o StrictHostKeyChecking=accept-new $WEB_USER@$WEB_SERVER bash deploy.sh "$CIRCLE_SHA1"

workflows:
  test_and_build_deploy:
    jobs:
      - test
      - build:
          requires:
          - test
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master

