version: 2.1

jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: Build docker image
          command: echo "=> Build"
  test:
    docker:
      - image: alpine:3.15
    steps:
      - run: 
          name: Test the app
          command: echo "=> Test"
  deploy:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: Deploy to AWS
          command: echo "=> Deploy"

workflows:
  jobs:
    - build 
    - test:
      requires:
        - build
    - deploy:
      requires:
        - test

