version: 2.1

jobs:
  test:
    docker:
      - image: alpine:3.15
    steps:
      - run: 
        name: Test the app
        command: |
          echo "=> Test"
  build:
    docker:
      - image: alpine:3.15
    steps:
      - run:
        name: Build docker image
        command: |
          echo "=> Build"
  deploy:
    docker:
      - image: alpine:3.15
    steps:
      - run:
        name: Deploy to AWS
        command: |
          echo "=> Deploy"

