# Generated by Django 3.0 on 2023-04-08 11:44

from django.db import migrations

def save_addresses(apps, schema_editor):
    old_address = apps.get_model('oc_lettings_site', 'Address')
    new_address = apps.get_model('lettings', 'Address')
    
    for addr in old_address.objects.all():
        a = new_address.objects.create(
            number=addr.number,
            street=addr.street,
            city=addr.city,
            state=addr.state,
            zip_code=addr.zip_code,
            country_iso_code=addr.country_iso_code
        )
        a.id = addr.id
        a.save()

def erase_addresses(apps, schema_editor):
    new_address = apps.get_model('lettings', 'Address')
    
    for addr in new_address.objects.all():
        addr.delete()

def save_lettings(apps, schema_editor):
    old_letting = apps.get_model('oc_lettings_site', 'Letting')
    old_address = apps.get_model('oc_lettings_site', 'Address')

    new_letting = apps.get_model('lettings', 'Letting')
    new_address = apps.get_model('lettings', 'Address')
    
    for letting in old_letting.objects.all():
        new_letting.objects.create(
            title=letting.title,
            address=new_address.objects.get(pk=letting.address.id)
        )

def erase_lettings(apps, schema_editor):
    new_letting = apps.get_model('lettings', 'Letting')
    
    for letting in new_letting.objects.all():
        letting.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(save_addresses, erase_addresses),
        migrations.RunPython(save_lettings, erase_lettings),
    ]
