# Generated by Django 3.0 on 2023-04-08 13:14

from django.db import migrations

def save_profiles(apps, schema_editor):
    old_profile = apps.get_model('oc_lettings_site', 'Profile')
    new_profile = apps.get_model('profiles', 'Profile')

    for profile in old_profile.objects.all():
        new_profile.objects.create(
            user=profile.user,
            favorite_city=profile.favorite_city
        )

def remove_profiles(apps, schema_editor):
    new_profile = apps.get_model('profiles', 'Profile')

    for profile in new_profile.objects.all():
        profile.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('oc_lettings_site', '0004_auto_20230408_1313'),
    ]

    operations = [
        migrations.RunPython(save_profiles, remove_profiles)
    ]
