# Generated by Django 3.0 on 2023-04-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0005_save_profiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
